[package]
name = "dinucorn"
version = "0.0.1"
authors = ["hallucino <d@t0t0.fr>"]
description = "Dino Unicorn Game :) - Unicorn Console"
documentation = ""
homepage = ""
repository = ""
readme = "README.md"
keywords = []
license = "MIT"

[dependencies]
getopts = "0.2.14"
log = "0.3.6"
fern = "0.3.5"
time = "0.1.35"

[dependencies.unicorn_sdl]
path = "../../unicorn-sdl"

[dependencies.unicorn]
path="../../unicorn"
features = []


[profile.dev]
opt-level = 2
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1